modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Dudblockman/psipherals"

[[mods]]
modId="psipherals"
displayName="Psionic Peripherals"
version="${version}"
authors="Dudblockman"
description='''
Fun and experimental additions to Psi
'''
[[dependencies.psipherals]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16-39,)"
    side="BOTH"

[[dependencies.psipherals]]
    modId="psi"
    mandatory=true
    versionRange="[r1.2-83,)"
    side="BOTH"

[[dependencies.psipherals]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.108,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.psipherals]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.16.1-3.0,)"
    ordering="AFTER"
    side="BOTH"
